# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  'Default'   #'Azure Pipelines' or 'Default'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    cd react_frontend
    npm i
  displayName: 'npm install'

- script: |
    cd react_frontend
    npm run build
  displayName: 'npm build'
    
- task: PublishPipelineArtifact@1
  inputs:
    path: 'react_frontend/build'
    artifact: 'MyBuildArtifact'

